# Generated by Django 5.1.6 on 2025-03-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='niveau',
        ),
    ]
